redactions = [
  "CONFLUENCE_PAT",
  "GOOGLE_API_KEY",
  "OPENROUTER_API_KEY"
]

[[env._.file]]
  path = "config.env.yaml"

[settings]
  experimental = true
  http_retries = 3
  task.timings = true
  verbose = false

[tools]
  jq = "latest"
  pandoc = "latest"
  "conda:htmd" = "latest"
  "conda:spider_cli" = "latest"
  "conda:xee-rust" = "latest"
  "github:block/goose" = "latest"
