redactions = [
  "CONFLUENCE_PAT",
  "GOOGLE_API_KEY",
  "OPENROUTER_API_KEY"
]

[[env._.file]]
  path = "config.env.yaml"

[settings]
  experimental = true
  task.timings = true
  verbose = true

[tools]
  jq = "latest"
  pandoc = "latest"
  "conda:htmd" = { version = "latest", depends = ["conda:libgcc"] }
  "conda:spider_cli" = { version = "latest", depends = ["conda:libgomp"] }
  "conda:xee-rust" = { version = "latest", depends = ["conda:_openmp_mutex"] }
  "github:block/goose" = "latest"
