name: Write newsletter draft to Confluence wiki

on:
  schedule:
    # Run every Wednesday at 00:00 UTC
    # We will filter for the second Wednesday in the job steps
    - cron: '0 0 * * 3'
  workflow_dispatch:
    inputs:
      ARTICLE_LINKS:
        description: 'URLs of the blog articles to be covered by the newsletter, separated by a space character'
        required: false
        type: string

jobs:
  gen-newsletter-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Check if second Wednesday
        id: check_date
        run: |
          DAY=$(date +%d)
          if [[ $DAY -ge 8 && $DAY -le 14 ]]; then
            echo "is_that_day=true" >> $GITHUB_ENV
          else
            echo "is_that_day=false" >> $GITHUB_ENV
            echo "Today is day $DAY, not the second Wednesday (days 8-14). Skipping workflow."
            exit 0
          fi

      - name: Checkout repository
        if: env.is_that_day == 'true' || github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v6

      - name: Set up mise (load env)
        if: env.is_that_day == 'true' || github.event_name == 'workflow_dispatch'
        env:
          MISE_ENV: github
        uses: jdx/mise-action@v4

      - name: Set up Pandoc
        if: env.is_that_day == 'true' || github.event_name == 'workflow_dispatch'
        uses: pandoc/actions/setup@v1.1.1

      - name: Install additional tools from source via Cargo
        if: env.is_that_day == 'true' || github.event_name == 'workflow_dispatch'
        run: |
          cargo install --bins --all-features htmd-cli spider_cli xee
          # test the installed tools
          htmd --version
          spider --version
          xee --version

      - name: Generate newsletter draft and write it to Confluence
        if: env.is_that_day == 'true' || github.event_name == 'workflow_dispatch'
        env:
          ARTICLE_LINKS: ${{ inputs.ARTICLE_LINKS || env.ARTICLE_LINKS }}
          CONFLUENCE_PAT: ${{ secrets.CONFLUENCE_PAT }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: |
          mise run newsletter_draft
